version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GROQ_API_KEY
      - GOOGLE_API_KEY
      - OPENAI_API_KEY
    depends_on:
      - redis
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -lc "pip install rq redis && rq worker specweaver"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  ui:
    build:
      context: ./frontend/ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
