version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - GROQ_API_KEY
      - GOOGLE_API_KEY
      - OPENAI_API_KEY
      - PYTHONPATH=/app/backend
    depends_on:
      - redis
    command: ["python", "/app/backend/start_api.py"]
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -lc "pip install rq redis && rq worker specweaver"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  ui:
    build:
      context: ./frontend/ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/workflows
    depends_on:
      - api
volumes:
  n8n_data:
