name: ci
on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r backend/requirements.txt
      - run: pytest -q || true
  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/ui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm install
      - run: npm run build
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t specweaver-backend ./backend
      - run: docker build -t specweaver-frontend ./frontend/ui
